services:
    storage:
        image: redis:latest
    counter:
        build: ./counter-app
        expose:
            - 5000
        ports:
            - 5000:5000
        environment:
            - PORT=5000
            - STORAGE_URL=storage
        depends_on:
            - storage
    library:
        build: ./library-app
        ports:
            - 80:3000
        environment: 
            - PORT=3000
            - COUNTER_API_URL=http://counter:5000
        depends_on:
            - counter